spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/account-db}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID:account.consumer}

topics:
  bank-account-activated: bank.account.activated

management:
  endpoints:
    web:
      exposure:
        include: health,info

clients:
  customer-service:
    base-url: ${CLIENTS_CUSTOMER_SERVICE_BASE_URL:http://localhost:8081}