spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/card-db}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID:card.consumer}

topics:
  bank-account-created: bank.account.created
  bank-debit-card-created: bank.debit.card.created

management:
  endpoints:
    web:
      exposure:
        include: health,info
