spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/customer-db}
      auto-index-creation: true
    redis:
      client-type: lettuce
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID:customer.consumer}

topics:
  bank-account-activated: bank.account.activated
  bank-credit-card-account-activated: bank.credit-card-account.activated

management:
  endpoints:
    web:
      exposure:
        include: health,info