eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: card-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

server:
  port: ${SERVER_PORT:8084}